# Rezept für Conda Umgebung

name: Quant
channels:
- conda-forge 
dependencies:
- python=3.11
- pip
# Web-Application
- streamlit
# Data Handling & Numerische Pakete
- pandas
- numpy
- pyarrow
# Statistik und Plotting
- statsmodels 
- matplotlib
# Finanzendaten-Abruf (YFinance)
- yfinance

# Pakete, die nur über Pip installiert werden können
- pip:
  - curl_cffi  # pip install curl_cffi
  - scikit-learn

