# Rezept f√ºr Conda Umgebung

name: Quant
channels:
- conda-forge 
dependencies:
- yfinance 
- python=3.11
# Web-Application
- streamlit
# Data Handling & Numerische Pakete
- pandas
- numpy
- pyarrow
# Statistik und Plotting
- statsmodels 
- matplotlib
# Finanzendaten-Abruf (YFinance)
- yfinance
- curl_cffi # pip install curl_cffi

